version: '3'

services:
    frontend:
        volumes: &appvolumes-frontend-mac
            - workspace_frontend:/var/www/html

    phpfpm:
        volumes: &appvolumes-mac
            - workspace:/var/www/html

    phpfpm_xdebug:
        volumes: *appvolumes-mac

    nginx:
        volumes: *appvolumes-mac

volumes:
    workspace:
    workspace_frontend:
