version: '3'

services:
    frontend:
        volumes:
            - ./frontend:/var/www/html

    phpfpm:
        volumes: &appvolumes-linux
            - ./backend:/var/www/html

    phpfpm_xdebug:
        volumes: *appvolumes-linux

    nginx:
        volumes: *appvolumes-linux
