version: '3'

services:
    nginx-frontend-proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
            - "${DEV_SERVER_PORT}:443"
        volumes:
            - ./config/ssl/certificates:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: unless-stopped
        depends_on:
            - frontend
        networks:
            - localswarm

    frontend:
        tty: true
        hostname: ${DEV_SERVER_HOST}
        image: aleksejsb/node:14-ssl
        volumes:
            - ./config/ssl:/usr/src/ssl:rw
        environment:
            VIRTUAL_HOST: ${DEV_SERVER_HOST}
            VIRTUAL_PORT: ${DEV_SERVER_PORT}
            DEV_SERVER_HOST: ${DEV_SERVER_HOST}
            SSL_CERTIFICATE_PATH: ${SSL_CERTIFICATE_PATH}
        expose:
            - ${DEV_SERVER_PORT}
        networks:
            - localswarm

    phpfpm:
        image: devallgento/php:7.4-fpm
        ports:
            - "2222:22"
        volumes: &appvolumes
            - ../.composer:/var/www/.composer:delegated
            - ./config/dockergento/nginx/conf/default.conf:/var/www/conf/nginx/default.conf:delegated
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        depends_on:
            - db
        networks:
            - localswarm

    phpfpm_xdebug:
        image: devallgento/php:7.4-fpm
        volumes: *appvolumes
        depends_on:
            - phpfpm
        networks:
            - localswarm

    varnish:
        image: devallgento/varnish
        ports:
            - 8081:80
        depends_on:
            - nginx
        environment:
            - VIRTUAL_PORT=80
        networks:
            - localswarm

    nginx:
        image: modestcoders/nginx:1.13
        ports:
            - 8081:8000
        volumes: *appvolumes
        depends_on:
            - phpfpm
            - phpfpm_xdebug
            - mailhog
            - elasticsearch
            - redis
        networks:
            - localswarm

    db:
        image: mysql:8
        hostname: mysql8
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: magento
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
        shm_size: '2gb'
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - localswarm
        command: --default-authentication-plugin=mysql_native_password

    redis:
        image: redis:latest
        networks:
            - localswarm
        volumes:
            - rddata:/data

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - localswarm

    elasticsearch:
        tty: true
        image: elasticsearch:7.7.1
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ELASTIC_USERNAME=username
            - ELASTIC_PASSWORD=password
        ports:
            - 9200:9200
        networks:
            - localswarm
        volumes:
            - esdata:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.7.1
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - localswarm

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - localswarm

volumes:
    dbdata:
    rddata:
    esdata:

networks:
    localswarm:
