version: "3.7"

services:
  phpfpm:
    image: modestcoders/php:7.1-fpm
    volumes: &appvolumes
      - ../.composer:/var/www/.composer:delegated
      - ../.composer:/var/www/html/var/composer_home:delegated
      - ./config/dockergento/nginx/conf/default.conf:/var/www/conf/nginx/default.conf:delegated
      - ./config/dockergento/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:delegated
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - db
    networks:
      - localswarm

  phpfpm_xdebug:
    image: modestcoders/php:7.1-fpm
    volumes: *appvolumes
    depends_on:
      - phpfpm
    networks:
      - localswarm

  nginx:
    image: modestcoders/nginx:1.13
    ports:
      - 80:8000
    volumes: *appvolumes
    depends_on:
      - phpfpm
      - phpfpm_xdebug
      - redis
    networks:
      - localswarm

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - localswarm

  node:
    image: modestcoders/node-php:node8-php7.1
    ports:
      - 35729:35729
    volumes: *appvolumes
    depends_on:
      - phpfpm
      - phpfpm_xdebug
    networks:
      - localswarm

  redis:
    image: redis:latest
    restart: always
    networks:
      - localswarm
    volumes:
      - rddata:/data

volumes:
  dbdata:
  sockdata:
  rddata:

networks:
  localswarm: