version: '3'

services:
    frontend:
        volumes: &appvolumes-linux
            - .:/var/www/html

    phpfpm:
        volumes: &appvolumes-linux
            - .:/var/www/html

    phpfpm_xdebug:
        volumes: *appvolumes-linux

    nginx:
        volumes: *appvolumes-linux
